name = "FusionTensors"
uuid = "e16ca583-1f51-4df0-8e12-57d32947d33e"
authors = ["ITensor developers <support@itensor.org> and contributors"]
version = "0.2.0"

[deps]
BlockArrays = "8e7c35d0-a365-5155-bbbb-fb81a777f24e"
BlockSparseArrays = "2c9a651f-6452-4ace-a6ac-809f4280fbb4"
BroadcastMapConversion = "4a4adec5-520f-4750-bb37-d5e66b4ddeb2"
GradedUnitRanges = "e2de450a-8a67-46c7-b59c-01d5a3d041c5"
HalfIntegers = "f0d1745a-41c9-11e9-1dd9-e5d34d218721"
LRUCache = "8ac3fa9e-de4c-5943-b1dc-09c6b5f20637"
LabelledNumbers = "f856a3a6-4152-4ec4-b2a7-02c1a55d7993"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
SparseArraysBase = "0d5efcca-f356-4864-8770-e1ed8d78f208"
Strided = "5e0ebb24-38b0-5f93-81fe-25c709ecae67"
SymmetrySectors = "f8a8ad64-adbc-4fce-92f7-ffe2bb36a86e"
TensorAlgebra = "68bd88dc-f39d-4e12-b2ca-f046b68fcc6a"
TypeParameterAccessors = "7e5a90cf-f82e-492e-a09b-e3e26432c138"
WignerSymbols = "9f57e263-0b3d-5e2e-b1be-24f2bb48858b"

[compat]
BlockArrays = "1.2.0"
BlockSparseArrays = "0.2.0"
BroadcastMapConversion = "0.1.0"
GradedUnitRanges = "0.1.1"
HalfIntegers = "1.6.0"
LRUCache = "1.6.1"
LabelledNumbers = "0.1.0"
LinearAlgebra = "1.10.0"
SparseArraysBase = "0.2.0"
Strided = "2.2.0"
SymmetrySectors = "0.1.1"
TensorAlgebra = "0.1.0"
TypeParameterAccessors = "0.2.0"
WignerSymbols = "2.0.0"
julia = "1.10"
